include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - directives_ordering       # ordena los imports automáticamente
    - prefer_single_quotes      # consistencia: siempre comillas simples
    - unnecessary_this          # evita this. innecesario
    - avoid_print               # usar debugPrint en vez de print
    - prefer_const_constructors # mejor rendimiento con const