// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxEASLM3ePZswQhCwMs6DAlVh3RXPlp9Q',
    appId: '1:538351334306:web:6c6ded44609132b8c538fb',
    messagingSenderId: '538351334306',
    projectId: 'sliding-puzzle-2243e',
    authDomain: 'sliding-puzzle-2243e.firebaseapp.com',
    storageBucket: 'sliding-puzzle-2243e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY6lC2dgJyzPlbM1lTXSrB5wnrooHjRs0',
    appId: '1:538351334306:android:542f38a19077345dc538fb',
    messagingSenderId: '538351334306',
    projectId: 'sliding-puzzle-2243e',
    storageBucket: 'sliding-puzzle-2243e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_25gE6rmxH5tvGjgg0I8surrO6GyQO8',
    appId: '1:538351334306:ios:2bb48de730f3b7fcc538fb',
    messagingSenderId: '538351334306',
    projectId: 'sliding-puzzle-2243e',
    storageBucket: 'sliding-puzzle-2243e.firebasestorage.app',
    iosBundleId: 'com.example.slidingPuzzle',
  );
}
